myapp/urls.py
from django.urls import path
from myapp import views
from myapp.views import IndexView, detailView, MyPasswordResetView, MyPasswordResetDoneView, MyPasswordResetConfirmView, \
    MyPasswordResetCompleteView, MyChangePasswordView, MyChangePasswordConfirmView
from django.contrib.auth.urls import views as auth_views
app_name = 'myapp'

urlpatterns = [
    # path(r'', views.index, name='index'),
    path(r'', IndexView.as_view(), name='index'),
    path(r'about', views.about, name='about'),
    path(r'<int:pk>', detailView.as_view(), name='detail'),
    # path(r'<int:book_id>', views.detail, name='detail'),
    path(r'findbooks', views.findbooks, name='findbooks'),
    path(r'place_order', views.place_order, name='place_order'),
    path(r'myorders', views.Myorders, name='myorders'),
    path(r'review', views.review, name='review'),
    path(r'register', views.register, name='register'),
    path(r'login', views.user_login, name='login'),
    path(r'chk_reviews/<int:book_id>', views.chk_reviews, name='chk_reviews'),
    path(r'logout', views.user_logout, name='logout'),
    path(r'password_reset/', MyPasswordResetView.as_view(), name='password_reset'),
    path(r'password_reset/done/', MyPasswordResetDoneView.as_view(), name='password_reset_done'),
    path(r'reset/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path(r'reset/done/', MyPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path(r'password_change/', MyChangePasswordView.as_view(), name='password_change'),
    path(r'password_change/done/', MyChangePasswordConfirmView.as_view(), name='password_change_done'),

    ]

mysiteF19/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # path(r'myapp/', include('myapp.urls1')),
    path(r'myapp/', include('myapp.urls')),
    path('myapp/', include('django.contrib.auth.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone
from upload_validator import FileTypeValidator

from .validator import maxvaluevalidator, minvaluevalidator
from django.core.validators import FileExtensionValidator, validate_image_file_extension


# Create your models here--------------
class Publisher(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField()
    city = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=20, default='USA')
    def __str__(self):
        return self.name


class Book(models.Model):
    CATEGORY_CHOICES = [
        ('S', 'Science&Tech'),
        ('F', 'Fiction'),
        ('B', 'Biography'),
        ('T', 'Travel'),
        ('O', 'Other')
    ]

    title = models.CharField(max_length=200)
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, default='S')
    num_pages = models.PositiveIntegerField(default=100)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[maxvaluevalidator, minvaluevalidator])
    publisher = models.ForeignKey(Publisher, related_name='books', on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    num_reviews = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.title

class Member(User):
    STATUS_CHOICES = {
        (1, 'Regular member'),
        (2, 'Premium Member'),
        (3, 'Guest Member'),
    }

    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    address = models.CharField(max_length=300, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province=models.CharField(max_length=2, default='ON')
    last_renewal = models.DateField(default=timezone.now)
    auto_renew = models.BooleanField(default=True)
    borrowed_books = models.ManyToManyField(Book, blank=True)
    avatar = models.FileField(upload_to='profile', help_text="Accepted format are .PNG, .JPEG, .JPG", blank=True, null=True)
    def books_borrowed(self):
        list1 = []
        for books in self.borrowed_books.all():
            list1.append(books.title)
        return list1



class Order(models.Model):
    ORDER_CHOICES = [
        (0, 'Purchase'),
        (1, 'Borrow')
    ]
    books = models.ManyToManyField(Book)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    order_type = models.IntegerField(choices=ORDER_CHOICES, default=1)
    order_date = models.DateField(default=timezone.now)
    # total_price = models.DecimalField(max_digits=10, decimal_places=2,  blank=True, null=True)
    def total_items(self):
        list1 = []
        for book in self.books.all():
            list1.append(book.title)
        return list1
    def total_books(self):
        return len(self.books.all())

    def __str__(self):
        return str(self.id) + " " + str(self.order_date)

class Review(models.Model):
    reviewer = models.EmailField()
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comments = models.TextField(blank=True, null=True)
    date = models.DateField(default=timezone.now)
    def __str__(self):
        return str(self.id) + " " + str(self.date)

myapp/forms.py
from django import forms
from myapp.models import Order, Review, Member, User


class SearchForm(forms.Form):
    CATEGORY_CHOICES = [
        ('S', 'Science&Tech'),
        ('F', 'Fiction'),
        ('B', 'Biography'),
        ('T', 'Travel'),
        ('O', 'Other')
    ]
    name = forms.CharField(label="Enter Your Name:", max_length=100, required=False)
    category = forms.ChoiceField(label="Select a Category:", widget=forms.RadioSelect, choices=CATEGORY_CHOICES,
                                 required=False)
    max_price = forms.IntegerField(label="Maximum Price:", min_value=0)


class RegisterForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['first_name', 'last_name', 'username', 'password', 'email', 'status', 'address', 'city', 'province', 'auto_renew', 'avatar']
        widgets = {'status': forms.RadioSelect(), 'auto_renew': forms.CheckboxInput()}
        labels = {'avatar': u'Profile Picture'}


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['books', 'order_type']
        widgets = {'books': forms.CheckboxSelectMultiple(), 'order_type': forms.RadioSelect}
        # labels = {'member': u'Member name', }



class ReviewForm(forms.ModelForm):
    class Meta:
        # Rating_choices = [
        #     (1, "Not so good"),
        #     (2, "Below Average"),
        #     (3, "Average"),
        #     (4, "Good"),
        #     (5, "Excellent")
        # ]
        model = Review
        fields = ['book', 'rating', 'comments']
        widgets = {
                   'book': forms.RadioSelect(),
                   'rating': forms.NumberInput(),
                   'comments': forms.Textarea()
                   }
        labels = {'reviewer': u"Please enter a valid Email Id", 'rating': u"Rating"}

myapp/views.py
import pytz
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.tokens import default_token_generator
from django.shortcuts import render, get_object_or_404, redirect, reverse, render_to_response
from datetime import datetime
from .models import Book, Review, Member, User, Order
from django.http import HttpResponse, HttpResponseRedirect
from .forms import SearchForm, OrderForm, ReviewForm, RegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from random import randint
from django.views.generic import ListView, DetailView
from django.contrib.auth.urls import views as auth_views


# Class based view
class IndexView(ListView):
    model = Book
    template_name = 'myapp/book_list.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        if 'last_login' in self.request.session:
            context['last_login'] = self.request.session['last_login']
        else:
            context['last_login'] = "Your last login was more than one hour ago!!"
        return context


# Create your views here.
# def index(request):
#     if 'last_login' in request.session:
#         last_login = request.session['last_login']
#     else:
#         last_login = "Your last login was more than one hour ago!!"
#     booklist = Book.objects.all().order_by('id')[:10]
#     return render(request, 'myapp/index.html', {'booklist': booklist, 'last_login': last_login})


def about(request):
    if 'number' in request.COOKIES:
        mynum = request.COOKIES['number']
        fav_number = render(request, 'myapp/about.html', {'mynum': mynum})
    else:
        mynum = randint(1, 100)
        fav_number = render(request, 'myapp/about.html', {'mynum': mynum})
        fav_number.set_cookie('number', mynum, 30)
    return fav_number
    # return  render(request, 'myapp/about.html')


class detailView(DetailView):
    model = Book
    template_name = 'myapp/book_detail.html'

    def get_queryset(self):
        return Book.objects.filter(id=self.kwargs['pk'])


# def detail(request, book_id):
#     book = get_object_or_404(Book, id=book_id)
#     return render(request, 'myapp/detail.html', {'book': book})


def findbooks(request):
    CATEGORY_CHOICES = {
        'S': 'Science&Tech',
        'F': 'Fiction',
        'B': 'Biography',
        'T': 'Travel',
        'O': 'Other'
    }
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            category = form.cleaned_data['category']
            max_price = form.cleaned_data['max_price']
            if (category):
                booklist = Book.objects.filter(category=category, price__lte=max_price)
                return render(request, 'myapp/results.html',
                              {'booklist': booklist, 'name': name, 'category': CATEGORY_CHOICES[category]})
            else:
                booklist = Book.objects.filter(price__lte=max_price)
                return render(request, 'myapp/results.html', {'booklist': booklist, 'name': name})

        else:
            return HttpResponse('Invalid data')
    else:
        form = SearchForm()
        return render(request, 'myapp/findbooks.html', {'form': form})


@login_required
def place_order(request):
    try:
        if Member.objects.get(id=request.user.id):
            if request.method == 'POST':
                form = OrderForm(request.POST)
                if form.is_valid():
                    order = form.save(commit=False)
                    books = form.cleaned_data['books']
                    # book = order.books
                    # order = form.save(commit=False)
                    # member = order.member
                    member = Member.objects.get(id=request.user.id)
                    order.member = member
                    total = 0
                    for b in books:
                        total += b.price
                    # order.total_price = total
                    type = order.order_type
                    order.save()
                    form.save_m2m()
                    if type == 1:
                        for b in order.books.all():
                            member.borrowed_books.add(b)

                    return render(request, 'myapp/order_response.html',
                                  {'books': books, 'order': order, 'total': total})
                else:
                    return render(request, 'myapp/placeorder.html', {'form': form})

            else:
                form = OrderForm()
                return render(request, 'myapp/placeorder.html', {'form': form})
    except Member.DoesNotExist:
        Member_err = "You are not a registered client"
        return render(request, 'myapp/placeorder.html', {'Member_err': Member_err})


@login_required
def review(request):
    try:
        if Member.objects.get(id=request.user.id, status__in=(1, 2)):
            if request.method == 'POST':
                form = ReviewForm(request.POST)
                if form.is_valid():
                    rating = form.cleaned_data['rating']
                    if rating <= 5 and rating >= 1:
                        reviews = form.save(commit=False)
                        books = reviews.book
                        books.num_reviews += 1
                        member = Member.objects.get(id=request.user.id)
                        reviews.reviewer = member.email
                        books.save()
                        reviews.save()
                        return redirect('myapp:index')
                    else:
                        RatingErr = "You must enter a rating between 1 and 5!"
                        return render(request, 'myapp/review.html', {'form': form, 'RatingErr': RatingErr})
                else:
                    return HttpResponse('Please fill the form correctly')

            else:
                form = ReviewForm()
                return render(request, 'myapp/review.html', {'form': form})
    except Member.DoesNotExist:
        Member_err = "You are not a registered client"
        return render(request, 'myapp/review.html', {'Member_err': Member_err})


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        valid_format = ['jpg', 'png', 'jpeg']
        if form.is_valid():
            print("Hi")
            image = form.cleaned_data['avatar']
            img = str(image).split('.')
            # print(img)
            if img[1] in valid_format:

                sign_up = form.save(commit=False)
                sign_up.password = make_password(form.cleaned_data['password'])
                sign_up.save()

                return index(request)
            else:

                Message_Err = "Wrong image format"
                return render(request, 'myapp/register.html', {'form': form, 'Message_Err': Message_Err})
        else:
            Message_Err = "Please fill all the fields correctly"
            return render(request, 'myapp/register.html', {'form': form, 'Message_Err': Message_Err})
    else:
        form = RegisterForm()
        return render(request, 'myapp/register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        current_login_time = datetime.now(pytz.timezone('America/Toronto'))
        timestamp = current_login_time.strftime("%d-%b-%Y (%H:%M:%S)")
        request.session['last_login'] = 'Last Login: ' + timestamp
        request.session.set_expiry(3600)
        if user:
            if user.is_active:
                login(request, user)
                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    return HttpResponseRedirect(reverse(('myapp:index')))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            # return HttpResponse('Invalid login details.')
            Member_err = "Please enter the details correctly"
            return render(request, 'myapp/login.html', {'Member_err': Member_err})
    else:
        return render(request, 'myapp/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


@login_required
def chk_reviews(request, book_id):
    try:
        if Member.objects.get(id=request.user.id):
            book = get_object_or_404(Book, id=book_id)
            total = 0
            avg_review = 0
            ratings = Review.objects.filter(book__id=book_id)
            if ratings:
                for r in ratings:
                    rate = r.rating
                    total += rate
                total_no_of_reviews = Book.objects.get(id=book_id).num_reviews
                avg_review = total / total_no_of_reviews
                return render(request, 'myapp/chk_reviews.html', {'book': book, 'avg_review': avg_review})
            else:
                Rating_err = "There are no reviews as of now"
                return render(request, 'myapp/chk_reviews.html', {'book': book, 'Rating_Err': Rating_err})
        # else:
        #     return HttpResponse("You are not a registered Client")
    except Member.DoesNotExist:
        Member_err = "You are not a registered client"
        return render(request, 'myapp/chk_reviews.html', {'Member_err': Member_err})


class MyPasswordResetView(auth_views.PasswordResetView):
    template_name = 'myapp/password_reset_form.html'
    # email_template_name = 'registration/password_reset_email.html'
    # extra_email_context={'new_password': '123459876'}
    def form_valid(self, form):

myapp/templates/myapp/about.html
{%  extends 'myapp/base.html' %}
{%  block title %}About page{% endblock %}
{% block body_block %}
    <body>
    <H1>This is an eBook APP </H1>
    {% if mynum %}
        <p>Your Favorite number is: {{ mynum }} </p>
    {% endif %}
    </body>
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is an eBook APP.</title>
</head>
<body>
<H1>This is an eBook APP </H1>
<a href="/myapp/">Back_HardCoded</a>
<br>
<a href="{% url 'myapp:index'%}">Back</a>
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
    <head>
{#        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">#}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
    </head>

        <nav class="navbar navbar-expand-sm bg-dark"
        {% block nav-style %}{% endblock %}">
            <div class="container p-none">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'myapp:index' %}"><b><i>Django Project</i></b></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">

                        <li class="nav-item"><a class="nav-link" href="{% url 'myapp:index' %}"><b>Home</b></a></li>
{#                        <li class="nav-item"><a class="nav-link" href="{% url 'myapp:register' %}"><b>Register</b></a></li>#}
                        <li class="nav-item"><a class="nav-link" href="{% url 'myapp:findbooks' %}"><b>Search Book</b></a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'myapp:place_order' %}"><b>Order</b></a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'myapp:about' %}"><b>About</b></a></li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
{#                            <li class="nav-item mr-auto ">#}

                                <li class="nav-item"><i style="color:white">Welcome {{ user.first_name }} </i></li>
                                {% if user.member.avatar.url %}
                                    <li class="nav-item"><img src="{{ user.member.avatar.url}}" width = "50" height = "50"></li>
                                {% endif %}
                        <li class="nav-item"><a class='nav-link' href="{% url 'password_change' %}"><b>Change Password</b></a></li>
                                <li class="nav-item"><a class='nav-link' href="{% url 'myapp:myorders' %}"><b>MyOrders</b></a></li>
                                <li class="nav-item"><a class='nav-link' href="{% url 'myapp:logout' %}"><b>Logout</b></a></li>
                    {% else %}
                            <li class="nav-item"><a class= 'nav-link' href="{% url 'myapp:login' %}"><b>Login</b></a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'myapp:register' %}"><b>Register</b></a></li>



                        {% endif %}
                       </ul>
                </div>
            </div>
        </nav>
        <title>eBook APP - {% block title %}Welcome!{% endblock %}</title>


    <body class="bodytag">
        <div class="bodycontent">

{#            <h1>{% block myhdg %}Hello {{ request.user.username|upper }} {% endblock %}</h1>#}
            {% block body_block %}*** {% endblock %}
        </div>
        <hr />
{#        <div>#}
{#            <ul>#}
{#                <li class="hbar1"><a href="/myapp/about">Find out about this site</a></li>#}
{#                <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>#}
{#                <li class="hbar1"><a href = "{%  url 'myapp:findbooks' %}">Find books</a></li>#}
{#                <li class="hbar1"><a href = "{%  url 'myapp:place_order' %}">Place Order</a></li>#}
{#            </ul>#}
{#        </div>#}
         <!-- Footer -->
</body>
    <footer class="page-footer fixed bottom">
        <div class= "navbar navbar-inverse navbar-static-bottom" role="navigation">
            <div class="navbar-text pull-left">
            </div>
            <div class= "navbar-text pull-right">
                <a href="{% url 'myapp:index' %}">
                    <b><i>Home</i></b></a>
            </div>
            <div class= "navbar-text pull-right">
                <a href="{% url 'myapp:findbooks' %}">
                    <b><i>Search Books</i></b></a>
            </div>
            <div class= "navbar-text pull-right">
                <a href="{% url 'myapp:place_order' %}">
                    <b><i>Place Order</i></b></a>
            </div>
            <div class= "navbar-text pull-right">
                <a href="{% url 'myapp:review' %}">
                    <b><i>Give Review</i></b></a>
            </div>
            <div class="navbar-text pull-left">
            &copy; UoW MAC Program, 2019
            </div>
        </div>
    </footer>


</html></html>

myapp/templates/myapp/book_detail.html
{%  extends 'myapp/base.html' %}

{% block body_block %}
    <body>
        <h3><i>Book Details</i></h3>
        <br/>
        <ol>
            <li class="list-group-item"><b>Title:</b> {{ book.title }}</li>
            <li class="list-group-item"><b>Price:</b> {{ book.price }} CAD</li>
            <li class="list-group-item"><b>Publisher:</b> {{ book.publisher }}</li>
        </ol>
        <a href="{% url 'myapp:chk_reviews' book.id %}"><button class="btn btn-success" > Check Reviews </button></a>

{#        <a href="{% url 'myapp:index' %}">Home</a>#}
    </body>
{% endblock %}

myapp/templates/myapp/chk_reviews.html
{%  extends 'myapp/base.html' %}

{% block body_block %}
    <body>
    {% if Member_err %}
        <h3><i>{{ Member_err }}</i></h3>
    {% else %}
        <h3><i>Book Reviews:</i></h3>
        <br/>
        <ol>
            <li class="list-group-item"><b>Title:</b> {{ book.title }}</li>
            {% if Rating_Err %}
               <li class="list-group-item"><b>Review:</b> {{ Rating_Err }}</li>
            {% else %}
                <li class="list-group-item"><b>Review:</b> {{ avg_review }}</li>
            {% endif %}
        </ol>
    {%  endif %}

{#        <a href="{% url 'myapp:index' %}">Home</a>#}
    </body>
{% endblock %}

myapp/templates/myapp/detail.html
{%  extends 'myapp/base.html' %}

{% block body_block %}
    <body>
        <h3><i>Book Details</i></h3>
        <br/>
        <ol>
            <li class="list-group-item"><b>Title:</b> {{ book.title }}</li>
            <li class="list-group-item"><b>Price:</b> {{ book.price }} CAD</li>
            <li class="list-group-item"><b>Publisher:</b> {{ book.publisher }}</li>
        </ol>
        <a href="{% url 'myapp:chk_reviews' book.id %}"><button class="btn btn-success" > Check Reviews </button></a>

{#        <a href="{% url 'myapp:index' %}">Home</a>#}
    </body>
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Detail</title>
</head>
<body>
    <h1>Book Details</h1>
    <ol>
        <li>Title: {{ book.title }}</li>
        <li>Price: {{ book.price }} CAD</li>
        <li>Publisher: {{ book.publisher }}</li>
    </ol>

<a href="{% url 'myapp:index' %}">Home</a>
</body>
</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
{#    {%  include 'index0.html' %}#}
    <body>

    {% if booklist %}
        <h4><i>{{ last_login }}</i></h4>
        <h2><i>List of Books:</i></h2>
        <br/>
        <div class="list-group">
        <ol>
            {% for book  in booklist %}
                <li class="list-group-item" ><a  href="{% url 'myapp:detail' book.id %}"> {{book.title}} </a>
                    <span class="badge badge-secondary float-right" >{{ book.num_reviews }}</span>
                </li>
            {% endfor %}
        </ol>
        </div>

    {% else %}
        <strong>There are no available books!</strong>
    {% endif %}


{#<p><a href="{%  url 'myapp:about' %}">About page</a></p>#}

</body>
{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

<body>

    {% block body_block %}
    {% if books %}
        <h2>Order Summary </h2>
        {% if order.order_type == 1 %}
            <h3>Below are the books Borrowed by {{ order.member.first_name }} :</h3>
        {%  else %}
            <h3>Below are the books Purchased by {{ order.member.first_name }} :</h3>
        {%  endif %}
            <h3>Total price : {{ total }}</h3>
        <ol>
            {% for b  in books %}
                <li> {{b.title}} </li>
            {% endfor %}
        </ol>

    {% else %}
        <strong>There are no available books!</strong>
    {% endif %}
    {%  endblock %}
</body>

myapp/templates/myapp/password_change_form.html
{% extends 'myapp/base.html' %}

{% block body_block %}
  <h1>Change your password?</h1>
 {%  if message_err %}
    <p><i style="color: red">{{ message_err }}</i></p>
{%  endif %}
  <form action="{% url 'myapp:password_change' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Change Password">
  </form>
{% endblock %}

myapp/templates/myapp/password_reset_complete.html
{% extends 'myapp/base.html' %}

{% block body_block %}
  <h1>Password reset complete</h1>
    <p>Your new password has been set. You can log in now on the <a href="{% url 'myapp:login' %}">log in page</a>.</p>
{% endblock %}

myapp/templates/myapp/password_reset_form.html
{% extends 'myapp/base.html' %}

{% block body_block %}
  <h1>Forgot your password?</h1>
  <p>Enter your email address below, and we'll email instructions for setting a new one.</p>
{%  if message_err %}
    <p><i style="color: red">{{ message_err }}</i></p>
{%  endif %}
  <form action="{% url 'myapp:password_reset' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send me instructions!">
  </form>
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}

    <form action="{% url 'myapp:place_order' %}" method="post">
        {% if Member_err %}
            <h4><i>{{ Member_err }}</i></h4>
        {% else %}
        <h3><i>Place your Order:</i></h3>
        <br/>
        {% csrf_token %}

            <div class="form-row">
                <div class="form-group col-md-3 mb-0">
                    {{ form.books|as_crispy_field }}
                </div>
                <div class="form-group col-md-3 mb-0">
                    {{ form.order_type|as_crispy_field }}
                </div>
    {#            <div class="form-group col-md-2 mb-0">#}
    {#                {{ form.member|as_crispy_field }}#}
    {#            </div>#}
            </div>

{#        {{ form.as_p }}#}
        <button type="submit" class="btn btn-success"> Place Order </button>
        {% endif %}
    </form>

{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}

{% load crispy_forms_tags %}
{% block body_block %}
    <form action="{% url 'myapp:register' %}" method="post" enctype="multipart/form-data">
        <h3><i> Registration Form:</i></h3>
        <br/>
        {% if Message_Err %}
        <h5><i>***** {{ Message_Err }} ******</i></h5>
        {% endif %}

        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-3 mb-0">
                {{ form.first_name|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.last_name|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.auto_renew|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-3 mb-0">
                {{ form.username|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.password|as_crispy_field }}
            </div>
            <div class="form-group col-md-1 mb-0">
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.email|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-3 mb-0">
                {{ form.address|as_crispy_field }}
            </div>
             <div class="form-group col-md-1 mb-0">
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.city|as_crispy_field }}
            </div>
             <div class="form-group col-md-1 mb-0">
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.province|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-3 mb-0">
                {{ form.avatar|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-3 mb-0">
                {{ form.status|as_crispy_field }}
            </div>
        </div>
        <button type="submit" class="btn btn-success"> Register </button>
    </form>

{% endblock %}